/**
 * The baked firing data the blog renders. Generated by
 * web/backend/scripts/export_firing.py from the backend SQLite, plus a
 * hand-authored curation layer for editorial bits. Static imports — no fetch,
 * no backend.
 */
import firing1 from "../data/firing-1.json";
import curation1 from "../data/firing-1.curation.json";

export type PizzaKind = "pizza" | "gap" | "note";

export interface SeriesPoint {
  /** Seconds since the firing started. */
  x: number;
  /** Oven air temperature inside the chiminea, °C. */
  c: number;
  /** True for an open-thermocouple fault reading (shown only in the raw view). */
  fault: boolean;
}

export interface PizzaSlot {
  seq: number;
  /** Pizza number 1..N (kind === "pizza" only); null for gaps and notes. */
  no: number | null;
  name: string;
  /** Seconds since firing start. */
  start: number;
  end: number | null;
  cook_min: number | null;
  kind: PizzaKind;
}

export interface Firing {
  id: number;
  started_at: string;
  ended_at: string | null;
  duration_s: number;
  sample_count: number;
  raw_max_c: number;
  clean_max_c: number;
  avg_c: number;
  fault_threshold_c: number;
  series: SeriesPoint[];
  pizzas: PizzaSlot[];
}

export interface Curation {
  title: string;
  dek: string;
  note_seqs: number[];
  fault_caption: string;
  pizza_blurbs: Record<string, string>;
}

export const firing1Data = firing1 as Firing;
export const firing1Curation = curation1 as Curation;
